name: EAS Android APK

on:
  workflow_dispatch: {}   # 수동 실행만

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      NODE_ENV: production            # Metro 경고 차단

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Align Expo SDK deps (best-effort)
        run: npx --yes expo install --fix || true

      - name: Install dependencies
        run: npm install

      - name: Build Android APK (preview)
        run: npx --yes eas-cli build -p android --profile preview --non-interactive

      - name: Show latest finished build
        run: npx --yes eas-cli build:list --status finished --limit 1
